# Generated by Django 4.2.7 on 2025-07-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarixi')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Kişi'), ('F', 'Qadın'), ('O', 'Digər')], max_length=1, verbose_name='Cins')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('address', models.TextField(blank=True, verbose_name='Ünvan')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şəhər')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Poçt Kodu')),
                ('newsletter_subscription', models.BooleanField(default=True, verbose_name='Xəbər Bülleteni')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='SMS Bildirişləri')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-mail Bildirişləri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'İstifadəçi Profili',
                'verbose_name_plural': 'İstifadəçi Profilləri',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ünvan Başlığı')),
                ('address_type', models.CharField(choices=[('home', 'Ev'), ('work', 'İş'), ('other', 'Digər')], default='home', max_length=10, verbose_name='Ünvan Növü')),
                ('full_address', models.TextField(verbose_name='Tam Ünvan')),
                ('city', models.CharField(max_length=100, verbose_name='Şəhər')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Rayon')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Poçt Kodu')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_default', models.BooleanField(default=False, verbose_name='Əsas Ünvan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Ünvan',
                'verbose_name_plural': 'Ünvanlar',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
