# Generated by Django 4.2.7 on 2025-08-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True, verbose_name='Cihaz ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Görünən Ad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Son Aktivlik')),
            ],
            options={
                'verbose_name': 'Anonim İstifadəçi',
                'verbose_name_plural': 'Anonim İstifadəçilər',
            },
        ),
    ]
