# Generated by Django 4.2.7 on 2025-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_anonymoususer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='display_name',
            field=models.CharField(default='', max_length=100, verbose_name='Görünən Ad'),
        ),
    ]
