# Generated by Django 4.2.7 on 2025-07-29 10:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('biography', models.TextField(blank=True, verbose_name='Bioqrafiya')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarixi')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Vəfat Tarixi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Foto')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Milliyyət')),
            ],
            options={
                'verbose_name': 'Müəllif',
                'verbose_name_plural': 'Müəlliflər',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Şəkil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nəşriyyat Adı')),
                ('address', models.TextField(blank=True, verbose_name='Ünvan')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Veb sayt')),
            ],
            options={
                'verbose_name': 'Nəşriyyat',
                'verbose_name_plural': 'Nəşriyyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Kitab Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('language', models.CharField(choices=[('az', 'Azərbaycan'), ('tr', 'Türk'), ('en', 'İngilis'), ('ru', 'Rus'), ('ar', 'Ərəb'), ('fa', 'Fars'), ('other', 'Digər')], default='az', max_length=10, verbose_name='Dil')),
                ('pages', models.PositiveIntegerField(verbose_name='Səhifə Sayı')),
                ('publication_date', models.DateField(verbose_name='Nəşr Tarixi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət (₼)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orijinal Qiymət (₼)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stok Miqdarı')),
                ('cover_image', models.ImageField(upload_to='books/covers/', verbose_name='Üz qabığı')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='books/backs/', verbose_name='Arxa qabıq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Seçilmiş')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Bestseller')),
                ('is_new', models.BooleanField(default=False, verbose_name='Yeni')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Baxış Sayı')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Satış Sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə Edilmə Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
                ('authors', models.ManyToManyField(to='books.author', verbose_name='Müəlliflər')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Kateqoriya')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publisher', verbose_name='Nəşriyyat')),
            ],
            options={
                'verbose_name': 'Kitab',
                'verbose_name_plural': 'Kitablar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reytinq')),
                ('comment', models.TextField(verbose_name='Rəy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Təsdiqlənmiş')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Kitab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Kitab Rəyi',
                'verbose_name_plural': 'Kitab Rəyləri',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
    ]
