# Generated by Django 4.2.7 on 2025-07-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together=set(),
        ),
    ]
