# Generated by Django 4.2.7 on 2025-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookreview_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Alt başlıq')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Şəkil')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklam Panosu',
                'verbose_name_plural': 'Reklam Panoları',
            },
        ),
    ]
