# Generated by Django 4.2.7 on 2025-08-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Şəkil'),
        ),
    ]
