# Generated by Django 4.2.7 on 2025-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Fəzilət Kitab', max_length=200, verbose_name='Sayt Adı')),
                ('site_description', models.TextField(default='Azərbaycanda ən böyük onlayn kitab mağazası. Minlərlə kitab, ən yaxşı qiymətlər və sürətli çatdırılma xidməti.', verbose_name='Sayt Təsviri')),
                ('phone', models.CharField(default='+994 12 345 67 89', max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(default='info@faziletkitab.az', max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, verbose_name='Ünvan')),
                ('working_hours', models.CharField(default='Bazar ertəsi - Cümə: 09:00-18:00', max_length=100, verbose_name='İş Saatları')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Sayt Tənzimləməsi',
                'verbose_name_plural': 'Sayt Tənzimləmələri',
            },
        ),
    ]
