# Generated by Django 4.2.7 on 2025-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_year',
            field=models.IntegerField(default=2024, verbose_name='Copyright İli'),
        ),
    ]
