# Generated by Django 4.2.7 on 2025-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='+994501234567', max_length=20, verbose_name='WhatsApp Nömrəsi'),
        ),
    ]
