# Generated by Django 4.2.7 on 2025-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_sitesettings_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo_imagekit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Foto ImageKit ID'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='Foto ImageKit URL'),
        ),
        migrations.AddField(
            model_name='banner',
            name='imagekit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ImageKit ID'),
        ),
        migrations.AddField(
            model_name='banner',
            name='imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='ImageKit URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='back_imagekit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arxa qabıq ImageKit ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='back_imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='Arxa qabıq ImageKit URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_imagekit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Üz qabığı ImageKit ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='Üz qabığı ImageKit URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='imagekit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ImageKit ID'),
        ),
        migrations.AddField(
            model_name='category',
            name='imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='ImageKit URL'),
        ),
    ]
