# Generated by Django 4.2.7 on 2025-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_author_photo_imagekit_id_author_photo_imagekit_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kitab Rəyi', 'verbose_name_plural': 'Kitab Rəyləri'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Footer Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_imagekit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Logo ImageKit ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='Footer Logo ImageKit URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Navbar Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_logo_imagekit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Navbar Logo ImageKit ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_logo_imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='Navbar Logo ImageKit URL'),
        ),
    ]
