# Generated by Django 4.2.7 on 2025-08-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_bookreview_options_sitesettings_footer_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_logo_imagekit_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_logo_imagekit_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_logo_imagekit_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_logo_imagekit_url',
        ),
    ]
