# Generated by Django 4.2.7 on 2025-08-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_bookreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kitab Rəyi', 'verbose_name_plural': 'Kitab Rəyləri'},
        ),
    ]
