# Generated by Django 4.2.7 on 2025-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_bookreview_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
