# Generated by Django 4.2.7 on 2025-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_delete_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt başlıq'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
    ]
