# Generated by Django 4.2.7 on 2025-09-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_banner_subtitle_alter_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nəşr Tarixi'),
        ),
    ]
