# Generated by Django 4.2.7 on 2025-08-08 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Mövzu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('sent', 'Göndərildi'), ('replied', 'Cavablandırıldı'), ('failed', 'Xəta')], default='pending', max_length=20, verbose_name='Status')),
                ('auto_reply_sent', models.BooleanField(default=False, verbose_name='Avtomatik cavab göndərildi')),
                ('auto_reply_date', models.DateTimeField(blank=True, null=True, verbose_name='Avtomatik cavab tarixi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Əlaqə mesajı',
                'verbose_name_plural': 'Əlaqə mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
