# Generated by Django 4.2.7 on 2025-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram')], max_length=20, verbose_name='Platforma')),
                ('url', models.URLField(verbose_name='Link')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='İkon CSS sinifi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Sosial media linki',
                'verbose_name_plural': 'Sosial media linkləri',
                'ordering': ['order', 'platform'],
                'unique_together': {('platform',)},
            },
        ),
    ]
