# Generated by Django 4.2.7 on 2025-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Gizlət'),
        ),
    ]
