# Generated by Django 4.2.7 on 2025-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_sitesettings_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
    ]
