# Generated by Django 4.2.7 on 2025-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_sitesettings_footer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Fəzilət Kitab', max_length=100, verbose_name='Sayt adı')),
                ('navbar_logo', models.ImageField(blank=True, null=True, upload_to='site/navbar/', verbose_name='Navbar Logo')),
                ('navbar_logo_imagekit_url', models.URLField(blank=True, null=True, verbose_name='Navbar Logo ImageKit URL')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='site/footer/', verbose_name='Footer Logo')),
                ('footer_logo_imagekit_url', models.URLField(blank=True, null=True, verbose_name='Footer Logo ImageKit URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Sayt Tənzimləməsi',
                'verbose_name_plural': 'Sayt Tənzimləmələri',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
    ]
