# Generated by Django 4.2.7 on 2025-08-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_logo_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
    ]
