# Generated by Django 4.2.7 on 2025-08-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_logo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Tənzimləmə', 'verbose_name_plural': 'Tənzimləmə'},
        ),
    ]
