# Generated by Django 4.2.7 on 2025-08-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_sitesettings_footer_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_logo_imagekit_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_logo_imagekit_url',
        ),
    ]
