# Generated by Django 4.2.7 on 2025-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_sitesettings_footer_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/footer/', verbose_name='Footer Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='Footer Logo ImageKit URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/navbar/', verbose_name='Navbar Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_logo_imagekit_url',
            field=models.URLField(blank=True, null=True, verbose_name='Navbar Logo ImageKit URL'),
        ),
    ]
