# Generated by Django 4.2.7 on 2025-07-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Səbət',
                'verbose_name_plural': 'Səbətlər',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Sifariş Nömrəsi')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('confirmed', 'Təsdiqləndi'), ('processing', 'Hazırlanır'), ('shipped', 'Göndərildi'), ('delivered', 'Çatdırıldı'), ('cancelled', 'Ləğv Edildi'), ('returned', 'Qaytarıldı')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Gözləyir'), ('paid', 'Ödənildi'), ('failed', 'Uğursuz'), ('refunded', 'Geri Qaytarıldı')], default='pending', max_length=20, verbose_name='Ödəniş Statusu')),
                ('payment_method', models.CharField(choices=[('cash', 'Nağd'), ('card', 'Kart'), ('bank_transfer', 'Bank Köçürməsi'), ('online', 'Onlayn Ödəniş')], default='cash', max_length=20, verbose_name='Ödəniş Üsulu')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ara Cəm')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Çatdırılma Qiyməti')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Endirim Məbləği')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ümumi Məbləğ')),
                ('delivery_name', models.CharField(max_length=200, verbose_name='Alıcı Adı')),
                ('delivery_phone', models.CharField(max_length=20, verbose_name='Alıcı Telefonu')),
                ('delivery_address_text', models.TextField(verbose_name='Çatdırılma Ünvanı (Mətn)')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Qeydləri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sifariş Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Göndərilmə Tarixi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Çatdırılma Tarixi')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='Çatdırılma Ünvanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('confirmed', 'Təsdiqləndi'), ('processing', 'Hazırlanır'), ('shipped', 'Göndərildi'), ('delivered', 'Çatdırıldı'), ('cancelled', 'Ləğv Edildi'), ('returned', 'Qaytarıldı')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dəyişiklik Tarixi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dəyişdirən')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Sifariş')),
            ],
            options={
                'verbose_name': 'Status Tarixçəsi',
                'verbose_name_plural': 'Status Tarixçələri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdar')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Kitab')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Sifariş')),
            ],
            options={
                'verbose_name': 'Sifariş Elementi',
                'verbose_name_plural': 'Sifariş Elementləri',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdar')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə Edilmə Tarixi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Kitab')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Səbət')),
            ],
            options={
                'verbose_name': 'Səbət Elementi',
                'verbose_name_plural': 'Səbət Elementləri',
                'unique_together': {('cart', 'book')},
            },
        ),
    ]
