# Generated by Django 4.2.7 on 2025-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_anonymous_user_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(max_length=50, verbose_name='Alıcı Telefonu'),
        ),
    ]
